name: Deploy
run-name: Deploy on branch ${{ github.ref_name }}

concurrency: ${{ vars.ENVIRONMENT }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ vars.RUNNER_NAME }}
    environment: ${{ vars.ENVIRONMENT }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ vars.WORKING_DIRECORY }}
    steps:
      - name: Enter maintenance mode
        run: ${{ vars.APPLICATION }} php artisan down
      - name: Pull the latest version of the app
        run: |
          cd backend
          git pull origin ${{ github.ref_name }}
      - name: Install composer dependencies
        run: ${{ vars.APPLICATION }} composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      - name: Clear the old cache
        run: ${{ vars.APPLICATION }} php artisan clear-compiled
      - name: Recreate cache
        run: ${{ vars.APPLICATION }} php artisan optimize
      - name: Run database migrations
        run: ${{ vars.APPLICATION }} php artisan migrate --force
      - name: Exit maintenance mode
        run: ${{ vars.APPLICATION }} php artisan up
