name: Context testing
run-name: Workflow triggered by @${{ github.actor }} on branch ${{ github.ref }}
on: workflow_dispatch

jobs:
  dump_contexts_to_log:
    runs-on: ${{ vars.RUNNER_NAME }} #ubuntu-latest
    steps:
      - name: WorkingDirectory
        shell: bash
        working-directory: ${{ github.ref_name }}
        run: echo ${{ vars.RUNNER_NAME }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo '$GITHUB_CONTEXT'
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo '$ENV_CONTEXT'
      - name: Dump vars context
        env:
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: echo '$VARS_CONTEXT'
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo '$JOB_CONTEXT'
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo '$STEPS_CONTEXT'
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo '$RUNNER_CONTEXT'
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo '$STRATEGY_CONTEXT'
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo '$MATRIX_CONTEXT'
      - name: Dump needs context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo '$NEEDS_CONTEXT'
      - name: Dump inputs context
        env:
          INPUTS_CONTEXT: ${{ toJson(inputs) }}
        run: echo '$INPUTS_CONTEXT'
